gallery_app/urls.py
from django.urls import path

from .views import gallery_view, add_photo

app_name = "gallery"
urlpatterns = [
    path('', gallery_view, name="gallery-view"),
    path('admin-area/add-photo/', add_photo, name="add-photo"),

]

home/urls.py
from django.urls import path

from .views import home_page, about_us, admin_area, add_game, all_games, user_list, delete_user, edit_user

app_name = "home"
urlpatterns = [
    path('', home_page, name="home-page"),
    path('about-us/', about_us, name="about-us"),
    path('admin-area/', admin_area, name="admin-area"),
    path('add-game/', add_game, name="add-game"),
    path('game/', all_games, name="game"),
    path('user-list/', user_list, name="user-list"),
    path('user/delete/<int:user_id>/', delete_user, name="user-delete"),
    path('user/edit/<int:user_id>/', edit_user, name="user-edit"),
]

olympic_project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static, serve

patterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls", namespace="home")),
    path('user/', include("user.urls", namespace="user")),
    path('gallery/', include("gallery_app.urls", namespace="gallery")),
    path('video/', include("video_app.urls", namespace="video")),
    path('schedule/', include("schedule_app.urls", namespace="schedule")),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    staticpatterns = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    staticpatterns = [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ]

urlpatterns = patterns + staticpatterns

schedule_app/urls.py
from django.urls import path

from .views import schedule, add_schedule

app_name = "schedule"
urlpatterns = [
    path('', schedule, name="schedule-all"),
    path('add/', add_schedule, name="schedule-add"),
]

user/urls.py
from django.urls import path

from .views import login_view, register_view, logout_view, change_password

app_name = "user"
urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('change-password/', change_password, name="change_password"),
]

video_app/urls.py
from django.urls import path

from .views import video_view, add_video, video_detail, add_comment_on_video

app_name = "video"
urlpatterns = [
    path('', video_view, name="video-view"),
    path('add/', add_video, name="video-add"),
    path('<int:id>/', video_detail, name="video-detail"),
    path('comment/<int:video_id>/', add_comment_on_video, name="add_comment_on_video"),
]

home/models.py
from django.db import models


class Game(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='games/')

    def __str__(self):
        return self.name

user/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _

from django_countries.fields import CountryField

from .managers import CustomUserManager


class User(AbstractBaseUser, PermissionsMixin):
    """
    email and password are required. Other fields are optional.
    """

    full_name = models.CharField(max_length=150)
    email = models.EmailField(unique=True,
                              error_messages={
                                  'unique': _("A user with this email already exists."),
                              },
                              )
    country = CountryField()
    is_staff = models.BooleanField('staff status', default=False)
    is_active = models.BooleanField('active', default=True)
    is_verified = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

home/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Game

User = get_user_model()


class CreateGamePostForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'image']


class UpdateUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ("full_name", "email", "country", "is_verified")

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django_countries.fields import CountryField

from .models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(help_text='Required. Add a valid email address')
    country = CountryField().formfield()

    class Meta:
        model = User
        fields = ("full_name", "email", "country", "password1", "password2")


class AccountAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError('Invalid email or password')

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib import messages

from django_countries import countries

from .models import Game

from .forms import CreateGamePostForm, UpdateUserForm

User = get_user_model()


def home_page(request):
    return render(request, "home/index.html")


def about_us(request):
    return render(request, "home/about-us.html")


def add_game(request):
    context = {}
    user = request.user
    if not user.is_superuser:
        return redirect('home:home-page')

    if request.method == 'POST':
        form = CreateGamePostForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Game added.')
    else:
        form = CreateGamePostForm()
    context['form'] = form
    return render(request, 'home/add-game.html', context)


def all_games(request):
    user = request.user
    if not user.is_authenticated:
        return redirect('user:login')
    games = Game.objects.all()
    context = {
        'games': games
    }
    return render(request, "home/all-games.html", context)


def user_list(request):
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request, "home/users.html", context)


def admin_area(request):
    return render(request, "home/admin-area.html")


def delete_user(request, user_id):
    user = User.objects.get(id=user_id)
    user.delete()
    return redirect('home:user-list')


def edit_user(request, user_id):
    if request.method == "POST":
        user = User.objects.get(id=user_id)
        form = UpdateUserForm(request.POST or None, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'User updated.')
    else:
        user = User.objects.get(id=user_id)
        form = UpdateUserForm(instance=user)
    context = {
        'form': form,
        'user': user,
        "countries": list(countries)
    }
    return render(request, "home/edit-user.html", context)

user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

from django_countries import countries

from .forms import RegistrationForm, AccountAuthenticationForm


def register_view(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Hurray! You are now registered user.')
    else:
        form = RegistrationForm()
    context = {
        "registration_form": form,
        "countries": list(countries)
    }
    return render(request, "user/register.html", context)


def login_view(request):
    context = {}

    if request.user.is_authenticated:
        return redirect("home:home-page")

    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                return redirect("home:home-page")

    else:
        form = AccountAuthenticationForm()

    context['login_form'] = form
    return render(request, 'user/login.html', context)


def logout_view(request):
    logout(request)
    return redirect('home:home-page')


def change_password(request):
    user = request.user
    if not user.is_authenticated:
        return  redirect("home:home-page")
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('user:change_password')
        # else:
        #     messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'user/change-password.html', {
        'form': form
    })

home/templates/home/about-us.html
{% extends 'base.html' %} {% block content %}
<div class="bg-light p-5 rounded">
  <h1>About Fun Olympic Game</h1>
  <p class="lead">
    The Olympic Games are an international sports event held every four years, once in the summer (the Summer Games) and once in the winter (the Winter Games) (the Winter Games). The Summer Games in 2012 were held in London, the Summer Games in 2016 in Rio de Janeiro, the Winter Games in 2014 in Sochi, Russia, and the Winter Games in 2018 in Pyeongchang, South Korea. The Olympic Games are officially known as the Games of the XXX Olympiad, with "XXX" representing the event's Roman numeral representation. For example, the 2008 Summer Olympics were officially known as the Games of the XXIX Olympiad.
  </p>
  <p class="lead">
    The Olympic Games are designed to bring together the world's best male and female competitors in a specific category of summer and winter sports. Winners of each of these competitions are now widely considered as the sport's champions for the four-year period after their victory.
  </p>
  <p class="lead">
    Men and women can compete in the Olympic Games, with the international governing organizations for the sports concerned establishing minimum and maximum age requirements (if any). The standard minimum age for participation in most Olympic sports is 16, however this varies by discipline. Marathon competitors, for example, must be at least 20 years old. The Youth Olympic Games, held in Singapore in 2010, inaugurated a new category of Olympic Games. Participants in the games have to be between the ages of 14 and 18.
  </p>
  <p class="lead">
    The sports featured in an Olympic event differ from one another. Since 1896, five sports have been included in each Summer Olympic Games: athletics, cycling, fencing, gymnastics, and swimming. For practically the whole time, a few sports, notably weightlifting and wrestling, were on the Olympic calendar. A variety of sports, including Basque pelota (1900 only), cricket (1900), rackets (1908), rugby sevens (2006), and water motorsports, have made brief debuts and then vanished from the games (1908). Cross-country skiing, figure skating, ice hockey, Nordic combined, ski jumping, and speed skating are among the seven sports included in all 21 Winter Olympic Games. Freestyle skiing and short-track speed skating are the two most recent winter sports (both introduced in 1992).
  </p>
</div>
<iframe
  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3532.924152309715!2d85.3469251151109!3d27.68873903291627!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb198bf9bd6c7d%3A0xb9e9193ddf9eda4f!2sISMT%20College!5e0!3m2!1sen!2snp!4v1639844675626!5m2!1sen!2snp"
  width="100%"
  height="300"
  style="border: 0"
  allowfullscreen=""
  loading="lazy"
></iframe>
{% endblock content %}

home/templates/home/add-game.html
{% extends "base.html" %} {% block content %}
<div class="mx-auto bg-light p-5 rounded" style="width: 50%">
  <h2 class="text-center">Add new game</h2>
  <br />
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row mb-3">
      <label for="name" class="col-sm-2 col-form-label">Game name</label>
      <div class="col-sm-10">
        <input
          type="text"
          class="form-control"
          id="name"
          name="name"
          required
          autofocus
        />
      </div>
    </div>
    <div class="row mb-3">
      <label for="image" class="col-sm-2 col-form-label">Game image</label>
      <div class="col-sm-10">
        <input
          type="file"
          class="form-control"
          id="image"
          name="image"
          required
          autofocus
        />
      </div>
    </div>
    {% if messages %}
    <ul style="color: rgb(25, 57, 202); list-style-type: none">
      {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
    <button type="submit" class="btn btn-primary">Add</button>
  </form>
</div>
{% endblock content %}

home/templates/home/admin-area.html
{% extends "base.html" %}

{% block content %}
        <div class="mx-auto bg-light p-5 rounded" style="width: 50%;">
            <h1>Welcome to admin area</h1>
        <h3>Being admin you can perform following tasks:</h3>
        <ul>
            <li><a href="{% url "gallery:add-photo" %}">Add photo to Gallery</a></li>
            <li><a href="{% url "video:video-add" %}">Upload video</a></li>
            <li><a href="{% url "home:add-game" %}">Add games</a></li>
            <li><a href="{% url "home:user-list" %}">Manage user</a></li>
            <li><a href="{% url "schedule:schedule-add" %}">Add game schedule</a></li>
        </ul>
    </div>
{% endblock content %}

home/templates/home/all-games.html
{% extends "base.html" %} {% load static %} {% block content %}
<link href="{% static 'css/carousel.css' %}" rel="stylesheet" />

<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
</style>
<div class="conatiner marketing">
  <div class="row">
    {% for game in games %}
    <div class="col-lg-2">
      <img
        class="bd-placeholder-img rounded-circle"
        src="{{ game.image.url }}"
        width="140"
        height="140"
      />
      <h2>{{ game.name }}</h2>
    </div>
    {% endfor %}
  </div>
  <!-- /.row -->
</div>
{% endblock content %}

home/templates/home/edit-user.html
{% extends "base.html" %}

{% block content %}
    <div class="mx-auto bg-light p-5 rounded" style="width: 50%;">
        <h2 class="text-center">Edit user</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="row mb-3">
                <label for="full_name" class="col-sm-2 col-form-label">Full name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="full_name" name="full_name" value="{{ user.full_name }}" required autofocus>
                </div>
            </div>
            <div class="row mb-3">
                <label for="email" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}" required>
                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>

                </div>
            </div>
            <div class="row mb-3">
                <label for="country" class="col-sm-2 col-form-label">Country</label>
                <div class="col-sm-10">
                    <select class="form-control" id="country" name="country" value="{{ user.country }}">
                        <option value="NP" selected="selected" name="country">{{ user.country }}</option>
                        {% for code, name in countries %}
                            <option value="{{ code }}" name="country">{{ name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            {% if messages %}
                <ul style="color: green; list-style-type: none;">
                    {% for message in messages %}
                        <li class="{{ message.tags }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <button type="submit" class="btn btn-primary">Edit user</button>
        </form>
    </div>
{% endblock content %}

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Custom styles for this template -->
    {#    <link href="https://getbootstrap.com/docs/5.1/examples/carousel/carousel.css" rel="stylesheet">#}
    <link href="https://getbootstrap.com/docs/5.1/examples/features/features.css" rel="stylesheet">
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="https://news.cgtn.com/news/2020-10-01/Olympics-Paris-2024-announce-measures-to-cut-cost-amid-pandemic-UeE1YhVkZy/img/4c23eec0ca0d4c039cb0edf000867185/4c23eec0ca0d4c039cb0edf000867185.png" class="bi" width="100%" height="100%"/>
                <div class="container">
                    <div class="carousel-caption text-start">
                        <h1>Fun Olympic Game</h1>
                        {% if request.user.is_authenticated %}
                            <p><a class="btn btn-lg btn-primary" href="{% url "user:register" %}">Let's have fun</a></p>
                        {% else %}
                            <p><a class="btn btn-lg btn-primary" href="{% url "user:register" %}">Register today</a></p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container px-4" id="custom-cards">
        <h2 class="pb-2 border-bottom">Features</h2>

        <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
            <div class="col">
                <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg"
                     style="background-image: url('/media/fig1.webp');">
                    <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                        <h2 class="pt-5 mt-5 mb-4 display-10 lh-1 fw-bold">Gymnastic</h2>
                        <ul class="d-flex list-unstyled mt-auto">
                            <li class="me-auto">
                                <img src="https://olympics.com/images/static/b2p-images/logo_color.svg"/>
                            </li>
                            <li class="d-flex align-items-center me-3">
                                <small>Nepal</small>
                            </li>
                            <li class="d-flex align-items-center">
                                <small>4d</small>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg"
                     style="background-image: url('/media/fig2.webp');">
                    <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                        <h2 class="pt-5 mt-5 mb-4 display-10 lh-1 fw-bold">Judo
                        </h2>
                        <ul class="d-flex list-unstyled mt-auto">
                            <li class="me-auto">
                                <img src="https://olympics.com/images/static/b2p-images/logo_color.svg"/>
                            </li>
                            <li class="d-flex align-items-center me-3">

                                <small>Nepal</small>
                            </li>
                            <li class="d-flex align-items-center">

                                <small>4d</small>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-5 shadow-lg"
                     style="background-image: url('/media/fig3.webp');">
                    <div class="d-flex flex-column h-100 p-5 pb-3 text-shadow-1">
                        <h2 class="pt-5 mt-5 mb-4 display-10 lh-1 fw-bold">Swimming</h2>
                        <ul class="d-flex list-unstyled mt-auto">
                            <li class="me-auto">
                                <img src="https://olympics.com/images/static/b2p-images/logo_color.svg"/>
                            </li>
                            <li class="d-flex align-items-center me-3">
                                <small>Nepal</small>
                            </li>
                            <li class="d-flex align-items-center">
                                <small>4d</small>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

home/templates/home/users.html
{% extends "base.html" %} {% block content %}
    <div class="mx-auto bg-light p-5 rounded">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Full name</th>
                <th scope="col">Email</th>
                <th scope="col">Country</th>
                <th scope="col">Verified</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.full_name }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.country }}</td>
                    <td>{{ user.is_verified }}</td>
                    <td>
                        <a href="{% url "home:user-edit" user.id %}">Edit</a>
                        ||
                        <a href="{% url "home:user-delete" user.id %}" onclick="return ask()">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        function ask() {
            return confirm('Are you sure you want to delete this user ?');
        }
    </script>
{% endblock content %}