home/urls.py
from django.urls import path

from .views import home_page, about_us, admin_area, add_game, all_games, user_list, delete_user, edit_user

app_name = "home"
urlpatterns = [
    path('', home_page, name="home-page"),
    path('about-us/', about_us, name="about-us"),
    path('admin-area/', admin_area, name="admin-area"),
    path('add-game/', add_game, name="add-game"),
    path('game/', all_games, name="game"),
    path('user-list/', user_list, name="user-list"),
    path('user/delete/<int:user_id>/', delete_user, name="user-delete"),
    path('user/edit/<int:user_id>/', edit_user, name="user-edit"),
]

olympic_project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static, serve

patterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls", namespace="home")),
    path('user/', include("user.urls", namespace="user")),
    path('gallery/', include("gallery_app.urls", namespace="gallery")),
    path('video/', include("video_app.urls", namespace="video")),
    path('schedule/', include("schedule_app.urls", namespace="schedule")),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    staticpatterns = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    staticpatterns = [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ]

urlpatterns = patterns + staticpatterns

video_app/urls.py
from django.urls import path

from .views import video_view, add_video, video_detail, add_comment_on_video

app_name = "video"
urlpatterns = [
    path('', video_view, name="video-view"),
    path('add/', add_video, name="video-add"),
    path('<int:id>/', video_detail, name="video-detail"),
    path('comment/<int:video_id>/', add_comment_on_video, name="add_comment_on_video"),
]

video_app/models.py
from django.db import models
from django.contrib.auth import get_user_model

from embed_video.fields import EmbedVideoField

User = get_user_model()


class Video(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/')
    # video_link = models.TextField()
    video_link = EmbedVideoField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

video_app/forms.py
from django import forms

from .models import Video, Comment


class CreateVideoPostForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title', 'image', 'video_link']


class CreateVideoCommentPostForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment', ]

video_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from .models import Video, Comment
from .forms import CreateVideoPostForm, CreateVideoCommentPostForm


def video_view(request):
    user = request.user
    if not user.is_authenticated:
        return redirect('home:home-page')
    videos = Video.objects.all()
    context = {
        'videos': videos
    }
    return render(request, 'video_app/videos.html', context)


def video_detail(request, id):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('home:home-page')
    video = Video.objects.get(id=id)
    # videos = Video.objects.all()
    videos = Video.objects.all()[:8]
    comments = Comment.objects.filter(video=video)
    context['video'] = video
    context['videos'] = videos
    context['comments'] = comments
    return render(request, 'video_app/video-view.html', context)


def add_video(request):
    context = {}
    user = request.user
    if not user.is_superuser:
        return redirect('home:home-page')

    if request.method == 'POST':
        form = CreateVideoPostForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Video uploaded.')
    else:
        form = CreateVideoPostForm()
    context['form'] = form
    return render(request, "video_app/add-video.html", context)


def add_comment_on_video(request, video_id):
    user = request.user
    if not user.is_authenticated:
        return redirect('home:home-page')

    video = Video.objects.get(id=video_id)
    if request.method == 'POST':
        Comment.objects.create(
            user=user,
            video=video,
            comment=request.POST['comment']
        )
        messages.success(request, 'Comment added.')
    return redirect('video:video-detail', video_id)

video_app/templates/video_app/add-video.html
{% extends "base.html" %} {% block content %}
    <div class="mx-auto bg-light p-5 rounded" style="width: 50%">
        <h2 class="text-center">Add new game schedule</h2>
        <br/>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row mb-3">
                <label for="title" class="col-sm-2 col-form-label"
                >Video title</label
                >
                <div class="col-sm-10">
                    <input
                            type="text"
                            class="form-control"
                            id="title"
                            name="title"
                            required
                    />
                </div>
            </div>
            <div class="row mb-3">
                <label for="video_link" class="col-sm-2 col-form-label"
                >Video link</label
                >
                <div class="col-sm-10">
                    <input
                            type="text"
                            class="form-control"
                            id="video_link"
                            name="video_link"
                            required
                    />
                </div>
            </div>
            <div class="row mb-3">
                <label for="image" class="col-sm-2 col-form-label">Preview image</label>
                <div class="col-sm-10">
                    <input type="file" class="form-control" id="image" name="image" required autofocus>
                </div>
            </div>
            {% if messages %}
                <ul style="color: rgb(128, 126, 0); list-style-type: none">
                    {% for message in messages %}
                        <li class="{{ message.tags }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <button type="submit" class="btn btn-primary">Add</button>
        </form>
    </div>
{% endblock content %}

video_app/templates/video_app/video-view.html
{% extends "base.html" %}
{% load embed_video_tags %}

{% block content %}
    <div class="row g-3">
        <div class="col-md-9">
            <div class="card shadow-sm">
                {% video video.video_link '100%x600' %}
            </div>
        </div>
        <div class="col-md-3">
            <div class="card shadow-sm">
                <h3>You may also like other videos</h3>
                {% for v in videos %}
                    <div class="card-body text-center">
                        <a href="{% url "video:video-detail" v.id %}">
                            <h5 class="card-title">{{ v.title }}</h5>
{#                            <img src="{{ v.image.url }}" style="width: 100px; height: 100px;" alt="">#}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-9">
            <div class="card shadow-sm">
                <h1>Comments</h1>
                <ul class="list-group list-group-numbered">
                    {% for comment in comments %}
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">{{ comment.user.full_name }}</div>
                            {{ comment.comment }}
                        </div>
                        <span class="badge bg-primary rounded-pill">Commented on {{ comment.created_at }}</span>
                    </li>
                    {% endfor %}

                </ul>
                <div class="mx-auto bg-light p-5 rounded" style="width: 50%;">
                    <form method="POST" action="{% url "video:add_comment_on_video" video.id  %}">
                        {% csrf_token %}
                        <div class="row mb-3">
                            <label for="comment" class="col-sm-2 col-form-label">Comment</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" id="comment" name="comment" required></textarea>
                            </div>
                        </div>
                        {% if messages %}
                            <ul style="color: green; list-style-type: none;">
                                {% for message in messages %}
                                    <li class="{{ message.tags }}">{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <button type="submit" class="btn btn-primary">Comment</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

video_app/templates/video_app/videos.html
{% extends "base.html" %}

{% block content %}
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for video in videos %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <a href="{% url "video:video-detail" video.id %}">
                                <img src="{{ video.image.url }}" class="bd-placeholder-img card-img-top"
                                 width="100%" height="225">
                            </a>

                        </div>
                    </div>
                    <!-- Modal -->
{#                    <div class="modal fade" id="viewImage" data-bs-backdrop="static" data-bs-keyboard="false"#}
{#                         tabindex="-1"#}
{#                         aria-labelledby="viewImageLabel" aria-hidden="true">#}
{#                        <div class="modal-dialog">#}
{#                            <div class="modal-content">#}
{#                                <div class="modal-header">#}
{#                                    <h5 class="modal-title" id="viewImageLabel">View image</h5>#}
{#                                    <button type="button" class="btn-close" data-bs-dismiss="modal"#}
{#                                            aria-label="Close"></button>#}
{#                                </div>#}
{#                                <div class="modal-body text-center">#}
{#                                    <img src="{{ photo.image.url }}" alt="">#}
{#                                </div>#}
{#                                <div class="modal-footer">#}
{#                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close#}
{#                                    </button>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
                    <!-- End Modal -->
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}