gallery_app/urls.py
from django.urls import path

from .views import gallery_view, add_photo

app_name = "gallery"
urlpatterns = [
    path('', gallery_view, name="gallery-view"),
    path('admin-area/add-photo/', add_photo, name="add-photo"),

]

home/urls.py
from django.urls import path

from .views import home_page, about_us, admin_area, add_game, all_games, user_list, delete_user, edit_user

app_name = "home"
urlpatterns = [
    path('', home_page, name="home-page"),
    path('about-us/', about_us, name="about-us"),
    path('admin-area/', admin_area, name="admin-area"),
    path('add-game/', add_game, name="add-game"),
    path('game/', all_games, name="game"),
    path('user-list/', user_list, name="user-list"),
    path('user/delete/<int:user_id>/', delete_user, name="user-delete"),
    path('user/edit/<int:user_id>/', edit_user, name="user-edit"),
]

olympic_project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static, serve

patterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls", namespace="home")),
    path('user/', include("user.urls", namespace="user")),
    path('gallery/', include("gallery_app.urls", namespace="gallery")),
    path('video/', include("video_app.urls", namespace="video")),
    path('schedule/', include("schedule_app.urls", namespace="schedule")),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    staticpatterns = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    staticpatterns = [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ]

urlpatterns = patterns + staticpatterns

schedule_app/urls.py
from django.urls import path

from .views import schedule, add_schedule

app_name = "schedule"
urlpatterns = [
    path('', schedule, name="schedule-all"),
    path('add/', add_schedule, name="schedule-add"),
]

user/urls.py
from django.urls import path

from .views import login_view, register_view, logout_view, change_password

app_name = "user"
urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('change-password/', change_password, name="change_password"),
]

video_app/urls.py
from django.urls import path

from .views import video_view, add_video, video_detail, add_comment_on_video

app_name = "video"
urlpatterns = [
    path('', video_view, name="video-view"),
    path('add/', add_video, name="video-add"),
    path('<int:id>/', video_detail, name="video-detail"),
    path('comment/<int:video_id>/', add_comment_on_video, name="add_comment_on_video"),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Fun Olympic Game</title>

</head>
<body style="background-color:  rgb(216, 189, 189)">
<main class="container" style="min-height: 85vh; height: 100%;">
    <header
            class="
            d-flex
            flex-wrap
            align-items-center
            justify-content-center justify-content-md-between
            py-3
            mb-4
            border-bottom
          "
    >
        <a
                href="/"
                class="
              d-flex
              align-items-center
              col-md-3
              mb-2 mb-md-0
              text-dark text-decoration-none
            "
        >
            <img src="https://olympics.com/images/static/b2p-images/logo_color.svg"/>
        </a>

        <ul
                class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0"
        >
            <li><a href="{% url "home:home-page" %}" class="nav-link px-2 link-dark">Home</a></li>
            {% if request.user.is_authenticated %}
                <li><a href="{% url "home:game" %}" class="nav-link px-2 link-dark">Games</a></li>
                <li><a href="{% url "schedule:schedule-all" %}" class="nav-link px-2 link-dark">Game Schedule</a></li>
                <li><a href="{% url "gallery:gallery-view" %}" class="nav-link px-2 link-dark">Gallery</a></li>
                <li><a href="{% url "video:video-view" %}" class="nav-link px-2 link-dark">Video</a></li>
            {% endif %}
            <li><a href="{% url "home:about-us" %}" class="nav-link px-2 link-dark">About Us</a></li>
            {% if request.user.is_superuser %}
                <li><a href="{% url "home:admin-area" %}" class="nav-link px-2 link-dark">Admin area</a></li>
            {% endif %}

        </ul>

        <div class="col-md-3 text-end">

            {% if user.is_authenticated %}
                <div class="btn-group">
                    <p type="button" class="dropdown-toggle" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        {{ request.user.email }}
                    </p>
                    <ul class="dropdown-menu">

                        <li><a class="dropdown-item" href="{% url "user:change_password" %}">Change password</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url "user:logout" %}">Logout</a></li>
                    </ul>
                </div>

            {% else %}
                <a class="btn btn-outline-primary me-2" href="{% url "user:login" %}" role="button">Login</a>
                <a class="btn btn-primary" href="{% url "user:register" %}" role="button">Register</a>
            {% endif %}
        </div>
    </header>
    {% block content %}

    {% endblock content %}


</main>
<footer class=" container d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <img src="https://olympics.com/images/static/b2p-images/logo_color.svg"/>
        </a>
        <span class="text-muted">&copy; 2022 All rights reserved - Fun Olympic Game</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3"><a class="text-muted" href="#">
            <img src="http://127.0.0.1:8000/media/facebook.jpg" class="bi" width="24" height="24"/>
        </a></li>
        <li class="ms-3"><a class="text-muted" href="#">
            <img src="http://127.0.0.1:8000/media/instagram.png" class="bi" width="24" height="24"/>
        </a></li>
        <li class="ms-3"><a class="text-muted" href="#">
            <img src="http://127.0.0.1:8000/media/twitter.png" class="bi" width="24" height="24"/>
        </a></li>
    </ul>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>